#
# Unicode版で追加した機能のメッセージ
#
set t(tool)                 "ツール"
set t(tool,encSettings)     "文字コードの設定..."
set t(tool,reloadRecList)   "文字コードを指定して音名リストを再読み込み"
set t(tool,converter)       "文字コード／ファイル名 変換ツール..."
set t(tool,language)        "表示言語 (Language)"
set t(tool,fixes)           "バグ修正の設定..."
set t(tool,restartMsg)      "再起動後に有効になります。"
set t(Version,unicode)      "Unicode版 (Python + Tk による再実装)\nオリジナル: OREMO 3.0-b190106 (c) nwp8861"
set t(readSettings,title)   "初期化ファイルの読み込み"

# 文字コードの設定
set t(enc,title)        "文字コードの設定"
set t(enc,read)         "読み込み (音名リスト・発声タイプ・コメント・BGM設定・ust)："
set t(enc,oto)          "oto.ini の書き出し："
set t(enc,comment)      "コメントファイルの書き出し："
set t(enc,reclist)      "音名リストの保存："
set t(enc,init)         "初期化ファイル (oremo-init.tcl)："
set t(enc,fallback)     "指定の文字コードで表現できない文字がある場合："
set t(enc,same)         "読み込み時と同じ"
set t(enc,noFallback)   "変換しない (? に置換)"
set t(enc,note)         "※ UTAU 用の oto.ini は通常 Shift_JIS です。\n※ Auto は BOM / UTF-8 / UTF-16 / Shift_JIS / GBK / Big5 を自動判別します。\n現在の音名リスト"
set t(enc,fallbackUsed) "(注意: 表現できない文字があったため \$enc で保存しました)"

# バグ修正の設定
set t(fix,title) "バグ修正の設定"
set t(fix,note)  "オリジナル OREMO 3.0-b190106 の不具合の修正です。チェックを外すとオリジナルと同じ動作になります。\n(F09 は再起動後に有効)"
set t(fix,all)   "全て選択"
set t(fix,none)  "全て解除"
set t(fix,F01)   "空の音名リストなどで操作するとエラーになる箇所、単独音oto.ini生成で推定対象の一部を外すとエラーになる箇所などを保護する"
set t(fix,F02)   "単独音oto.ini生成が表示中の波形を他のwavで上書きしてしまい、未保存の録音が失われたり別の音名で保存される問題を修正"
set t(fix,F03)   "ショートカット設定の「自動録音停止」が手動録音停止に割り当てられて機能しない問題を修正"
set t(fix,F04)   "ショートカットを設定し直したとき、以前に割り当てたキーを解除する"
set t(fix,F05)   "詳細設定の「キャンセル」で、窓を開いている間に移動した収録位置などまで巻き戻る問題を修正 (設定項目のみ戻す)"
set t(fix,F06)   "パワー・F0・oto.ini自動推定・MFCC補正で、wavの実際のサンプリング周波数を使う (オリジナルは設定値または44100Hz固定)"
set t(fix,F07)   "ガイドBGM設定ファイルの時刻単位 sample が使えない問題を修正"
set t(fix,F08)   "初期化ファイルで「\[」が保存のたびに「\\\[」へ化ける問題、「;」を含む値があるとファイル全体が読み込まれない問題を修正"
set t(fix,F09)   "オーディオI/O設定(デバイス・PortAudio設定)を保存し、次回起動時に復元する"
set t(fix,F10)   "ustから発声リストを作るとき、休符「R」と空の歌詞を除外する"
set t(fix,F11)   "他の音を再生中でも音叉・BGM試聴・自動録音を開始できるようにする (オリジナルは状態だけ変わり音が鳴らない)"
set t(fix,F12)   "修飾キー付きの録音ショートカットで、修飾キーを先に離すと録音が止まらない問題を修正"
set t(fix,F13)   "詳細設定でサンプリング周波数を変えると、表示中の音のサンプリング周波数だけ書き換わり再生速度が変わる問題を修正"
set t(fix,F14)   "「コメントファイルの読み込み」でキャンセルすると全コメントが消え、終了時にコメントファイルが削除される問題を修正"
set t(fix,F15)   "oto.ini生成前の未保存確認で「キャンセル」を押しても生成画面が開く問題を修正"
set t(fix,F16)   "連続音oto.ini生成で休符やエイリアス上限で除外されたモーラがあると、MFCC補正が前のwavの行まで二重に補正する問題を修正"

# 変換ツール
set t(conv,title)       "文字コード／ファイル名 変換ツール"
set t(conv,tabContent)  "ファイル内容の文字コード変換"
set t(conv,tabName)     "文字化けファイル名の修復"
set t(conv,tabText)     "文字列の修復"
set t(conv,addFiles)    "ファイル追加..."
set t(conv,addFolder)   "フォルダ追加..."
set t(conv,remove)      "削除"
set t(conv,clear)       "クリア"
set t(conv,src)         "変換元："
set t(conv,dst)         "変換先："
set t(conv,newline)     "改行："
set t(conv,keep)        "そのまま"
set t(conv,backup)      "バックアップ(.bak)を作る"
set t(conv,run)         "変換実行"
set t(conv,file)        "ファイル"
set t(conv,detected)    "判定した文字コード"
set t(conv,status)      "状態"
set t(conv,unencodable) "変換先で表現できない文字"
set t(conv,done)        "完了しました"
set t(conv,folder)      "フォルダ："
set t(conv,recursive)   "サブフォルダも含む"
set t(conv,dirs)        "フォルダ名も対象"
set t(conv,wrong)       "誤って使われた文字コード："
set t(conv,real)        "本来の文字コード："
set t(conv,scan)        "スキャン"
set t(conv,current)     "現在の名前"
set t(conv,new)         "修復後の名前"
set t(conv,how)         "方法"
set t(conv,invalid)     "使用できない文字"
set t(conv,exists)      "同名ファイルあり"
set t(conv,renamed)     "変更済み"
set t(conv,nameNote)    "※ 選択した行だけ名前を変更します。"
set t(conv,undo)        "元に戻す"
set t(conv,rename)      "選択した名前を変更"
set t(conv,nothing)     "文字化けしたファイル名は見つかりませんでした。"
set t(conv,textNote)    "文字化けした文字列を貼り付けてください (候補をダブルクリックでコピー)："
set t(conv,repair)      "修復"
set t(conv,candidate)   "候補"

# 高DPI / zoom
set t(tool,uiScale)         "表示倍率"
set t(tool,uiScaleAuto)     "自動 (Windowsの拡大率に合わせる)"
set t(tool,dpiAware)        "高解像度ディスプレイでくっきり表示"

# font family
set t(fontWindow,family)     "フォント"
set t(fontWindow,auto)       "自動 (リストの文字をすべて表示できるフォント)"
set t(fontWindow,familyNote) "※ フォントの変更はすぐに反映されます"
