#
# Unicode版新增功能的消息 (简体中文)
#
set t(tool)                 "工具"
set t(tool,encSettings)     "文字编码设置..."
set t(tool,reloadRecList)   "以指定编码重新读取录音表"
set t(tool,converter)       "文字编码／文件名 转换工具..."
set t(tool,language)        "界面语言 (Language)"
set t(tool,fixes)           "BUG修正设置..."
set t(tool,restartMsg)      "重启后生效。"
set t(Version,unicode)      "Unicode版 (使用 Python + Tk 重新实现)\n原版: OREMO 3.0-b190106 (c) nwp8861"
set t(readSettings,title)   "读取初始化文件"

# 文字编码设置
set t(enc,title)        "文字编码设置"
set t(enc,read)         "读取 (录音表・发声类型・备注・BGM设置・ust)："
set t(enc,oto)          "写出 oto.ini："
set t(enc,comment)      "写出备注文件："
set t(enc,reclist)      "保存录音表："
set t(enc,init)         "初始化文件 (oremo-init.tcl)："
set t(enc,fallback)     "指定编码无法表示某些字符时："
set t(enc,same)         "与读取时相同"
set t(enc,noFallback)   "不改用其他编码 (替换为 ?)"
set t(enc,note)         "※ UTAU 用的 oto.ini 通常为 Shift_JIS。\n※ Auto 会自动识别 BOM / UTF-8 / UTF-16 / Shift_JIS / GBK / Big5。\n当前录音表"
set t(enc,fallbackUsed) "(注意: 含有无法表示的字符，已改用 \$enc 保存)"

# BUG修正设置
set t(fix,title) "BUG修正设置"
set t(fix,note)  "以下为原版 OREMO 3.0-b190106 中缺陷的修正。取消勾选即与原版行为完全一致。\n(F09 重启后生效)"
set t(fix,all)   "全选"
set t(fix,none)  "全不选"
set t(fix,F01)   "保护会导致报错的操作：录音表为空时切换、单独音oto.ini生成时取消部分推定对象等"
set t(fix,F02)   "修正单独音oto.ini生成会用其他wav覆盖当前显示的波形，导致未保存录音丢失或被存成错误音名的问题"
set t(fix,F03)   "修正快捷键设置中「停止自动录音」被绑定到手动停止录音而不起作用的问题"
set t(fix,F04)   "重新设置快捷键时，解除之前分配的按键"
set t(fix,F05)   "修正高级设置「取消」时，连窗口打开期间切换的录音位置等也被回滚的问题 (只恢复设置项)"
set t(fix,F06)   "响度・F0・oto.ini自动推定・MFCC修正使用wav实际的采样率 (原版使用设置值或固定44100Hz)"
set t(fix,F07)   "修正引导BGM设置文件的时间单位 sample 无法使用的问题"
set t(fix,F08)   "修正初始化文件中「\[」每次保存都变成「\\\[」、以及含「;」的值会导致整个文件不被读取的问题"
set t(fix,F09)   "保存音频I/O设置(设备・PortAudio设置)，下次启动时恢复"
set t(fix,F10)   "从ust生成发声列表时，排除休止符「R」和空歌词"
set t(fix,F11)   "其他声音播放中也能启动音叉・BGM试听・自动录音 (原版只改变状态但不发声)"
set t(fix,F12)   "修正带修饰键的录音快捷键在先松开修饰键时录音无法停止的问题"
set t(fix,F13)   "修正在高级设置中更改采样率时，当前显示音频的采样率被改写、播放速度改变的问题"
set t(fix,F14)   "修正「读取备注文件」中按取消会清空全部备注、退出时还会删除备注文件的问题"
set t(fix,F15)   "修正生成oto.ini前的未保存确认中按「取消」仍会打开生成窗口的问题"
set t(fix,F16)   "修正连续音oto.ini生成时，若有因休止符或别名上限被排除的音拍，MFCC修正会波及前一个wav的行并重复修正的问题"

# 转换工具
set t(conv,title)       "文字编码／文件名 转换工具"
set t(conv,tabContent)  "文件内容编码转换"
set t(conv,tabName)     "修复乱码文件名"
set t(conv,tabText)     "修复字符串"
set t(conv,addFiles)    "添加文件..."
set t(conv,addFolder)   "添加文件夹..."
set t(conv,remove)      "移除"
set t(conv,clear)       "清空"
set t(conv,src)         "源编码："
set t(conv,dst)         "目标编码："
set t(conv,newline)     "换行："
set t(conv,keep)        "保持不变"
set t(conv,backup)      "创建备份(.bak)"
set t(conv,run)         "执行转换"
set t(conv,file)        "文件"
set t(conv,detected)    "识别出的编码"
set t(conv,status)      "状态"
set t(conv,unencodable) "目标编码无法表示的字符"
set t(conv,done)        "已完成"
set t(conv,folder)      "文件夹："
set t(conv,recursive)   "包含子文件夹"
set t(conv,dirs)        "也处理文件夹名"
set t(conv,wrong)       "被错误使用的编码："
set t(conv,real)        "原本的编码："
set t(conv,scan)        "扫描"
set t(conv,current)     "当前名称"
set t(conv,new)         "修复后的名称"
set t(conv,how)         "方式"
set t(conv,invalid)     "含非法字符"
set t(conv,exists)      "已有同名文件"
set t(conv,renamed)     "已重命名"
set t(conv,nameNote)    "※ 只重命名选中的行。"
set t(conv,undo)        "撤销"
set t(conv,rename)      "重命名选中项"
set t(conv,nothing)     "没有发现乱码文件名。"
set t(conv,textNote)    "请粘贴乱码字符串 (双击候选项可复制)："
set t(conv,repair)      "修复"
set t(conv,candidate)   "候选"

# 高DPI / zoom
set t(tool,uiScale)         "界面缩放"
set t(tool,uiScaleAuto)     "自动 (跟随Windows缩放比例)"
set t(tool,dpiAware)        "高分辨率屏幕清晰显示"

# font family
set t(fontWindow,family)     "字体"
set t(fontWindow,auto)       "自动 (选择能显示列表中全部文字的字体)"
set t(fontWindow,familyNote) "※ 字体的更改立即生效"
set t(tool,korede)          "KOREDE (引导BGM设置文件制作)..."
