set t(tool)                 "Tools"
set t(tool,encSettings)     "Encoding settings..."
set t(tool,reloadRecList)   "Reload reclist with encoding"
set t(tool,converter)       "Encoding / file name converter..."
set t(tool,language)        "Language"
set t(tool,fixes)           "Bug fix switches..."
set t(tool,restartMsg)      "Takes effect after restarting OREMO."
set t(Version,unicode)      "Unicode edition (Python + Tk rewrite)\nOriginal: OREMO 3.0-b190106 (c) nwp8861"
set t(readSettings,title)   "Open init file"

set t(enc,title)        "Encoding settings"
set t(enc,read)         "Reading (reclist, type list, comments, BGM setting, ust):"
set t(enc,oto)          "Writing oto.ini:"
set t(enc,comment)      "Writing comment file:"
set t(enc,reclist)      "Saving reclist:"
set t(enc,init)         "Init file (oremo-init.tcl):"
set t(enc,fallback)     "If a character cannot be encoded:"
set t(enc,same)         "Same as when read"
set t(enc,noFallback)   "None (replace with ?)"
set t(enc,note)         "* oto.ini for UTAU is normally Shift_JIS.\n* Auto detects BOM / UTF-8 / UTF-16 / Shift_JIS / GBK / Big5.\nCurrent reclist"
set t(enc,fallbackUsed) "(Note: saved as \$enc because of characters the chosen encoding cannot hold)"

set t(fix,title) "Bug fix switches"
set t(fix,note)  "Fixes for bugs of the original OREMO 3.0-b190106. Unchecked = identical to the original.\n(F09 takes effect after restarting)"
set t(fix,all)   "All"
set t(fix,none)  "None"
set t(fix,F01)   "Guard operations that raise errors (empty reclist, unchecked targets in single oto.ini estimation, ...)"
set t(fix,F02)   "Single oto.ini estimation no longer replaces the displayed sound (unsaved takes were lost or saved under a wrong name)"
set t(fix,F03)   "The 'Stop auto recording' shortcut was bound to the manual stop and did nothing"
set t(fix,F04)   "Release previously assigned keys when shortcuts are changed"
set t(fix,F05)   "'Cancel' in Detailed settings restores only the settings (not the current item etc.)"
set t(fix,F06)   "Use the real sampling rate of the wav for power / F0 / oto.ini estimation / MFCC (original: setting value or 44100 Hz)"
set t(fix,F07)   "Time unit 'sample' in guide BGM setting files did not work"
set t(fix,F08)   "Init file: '\[' turned into '\\\[' on every save; a value containing ';' made the whole file rejected"
set t(fix,F09)   "Save audio I/O settings and restore them at start up"
set t(fix,F10)   "Skip rests 'R' and empty lyrics when making a list from a ust"
set t(fix,F11)   "Tuning fork / BGM preview / auto recording can start while something else is playing"
set t(fix,F12)   "Recording shortcut with a modifier did not stop when the modifier was released first"
set t(fix,F13)   "Changing the sampling rate relabelled the displayed sound (wrong speed)"
set t(fix,F14)   "Cancelling 'Open comment file' erased all comments (and the comment file on exit)"
set t(fix,F15)   "'Cancel' in the unsaved-wav check before oto.ini generation did not cancel"
set t(fix,F16)   "Continuous oto.ini: MFCC correction reached into the previous wav's rows when morae were skipped"

set t(conv,title)       "Encoding / file name converter"
set t(conv,tabContent)  "File contents"
set t(conv,tabName)     "Garbled file names"
set t(conv,tabText)     "Text repair"
set t(conv,addFiles)    "Add files..."
set t(conv,addFolder)   "Add folder..."
set t(conv,remove)      "Remove"
set t(conv,clear)       "Clear"
set t(conv,src)         "From:"
set t(conv,dst)         "To:"
set t(conv,newline)     "Newline:"
set t(conv,keep)        "keep"
set t(conv,backup)      "Make .bak backup"
set t(conv,run)         "Convert"
set t(conv,file)        "File"
set t(conv,detected)    "Detected"
set t(conv,status)      "Status"
set t(conv,unencodable) "cannot encode"
set t(conv,done)        "Done"
set t(conv,folder)      "Folder:"
set t(conv,recursive)   "Include sub folders"
set t(conv,dirs)        "Rename folders too"
set t(conv,wrong)       "Shown as:"
set t(conv,real)        "Real encoding:"
set t(conv,scan)        "Scan"
set t(conv,current)     "Current name"
set t(conv,new)         "New name"
set t(conv,how)         "Method"
set t(conv,invalid)     "invalid char"
set t(conv,exists)      "exists"
set t(conv,renamed)     "renamed"
set t(conv,nameNote)    "* Only selected rows are renamed."
set t(conv,undo)        "Undo"
set t(conv,rename)      "Rename selected"
set t(conv,nothing)     "No garbled names found."
set t(conv,textNote)    "Paste garbled text (double click a candidate to copy):"
set t(conv,repair)      "Repair"
set t(conv,candidate)   "Candidate"

# 高DPI / zoom
set t(tool,uiScale)         "UI zoom"
set t(tool,uiScaleAuto)     "Auto (Windows scaling)"
set t(tool,dpiAware)        "Sharp display on high DPI screens"

# font family
set t(fontWindow,family)     "Font"
set t(fontWindow,auto)       "Auto (a font that has every character of the lists)"
set t(fontWindow,familyNote) "* The font change takes effect immediately"
set t(tool,korede)          "KOREDE (guide BGM setting file maker)..."
