#--------------------------------
# font used for lists / labels (falls back automatically if missing)
set t(fontName) "MS Gothic"

set t(.confm)        "Confirm"
set t(.confm.r)      "Read"
set t(.confm.nr)     "Don't read"
set t(.confm.fioErr) "File I/O error"
set t(.confm.yes)    "Yes"
set t(.confm.no)     "No"
set t(.confm.ok)     "OK"
set t(.confm.apply)  "Apply"
set t(.confm.run)    "Run"
set t(.confm.c)      "Cancel"
set t(.confm.errTitle) "Error"
set t(.confm.warnTitle) "Warning"
set t(.confm.delParam)  "The current parameters will be erased. OK?"

set t(makeRecListFromDir,q)  "Read the oto.ini file?"
set t(makeRecListFromDir,a)  "Generate parameters automatically"

set t(makeRecListFromUst,title1)    "Open ust file"
set t(makeRecListFromUst,errMsg)    "Could not read the ust file"
set t(makeRecListFromUst,doneMsg)   "The ust file was read"

set t(genParamWizard,title)  "Kind of voice data"
set t(genParamWizard,q)      "Choose the kind of voice data."
set t(genParamWizard,a1)     "Single utterances"
set t(genParamWizard,a2)     "Continuous utterances"

set t(saveRecList,title)     "Save reclist"
set t(saveRecList,errMsg)    "Could not write \$v(recListFile)"
set t(saveRecList,errMsg2)   "Could not write the names"
set t(saveRecList,doneMsg)   "Reclist saved to \$v(recListFile)"

set t(saveCommentList,errMsg) "Could not save the comments"

set t(readRecList,title1)    "Open reclist"
set t(readRecList,errMsg)    "Could not read the reclist (\$v(recListFile))"
set t(readRecList,errMsg2)   "Could not read the names"
set t(readRecList,doneMsg)   "\$v(recListFile) was read"
set t(readRecList,overwrite) "The reclist folder has a comment file. Discard the current comments and read it?"

set t(readCommentList,errMsg)   "Could not read the comments"
set t(readCommentList,doneMsg)  "\"\$commNum comments were read\""
set t(readCommentList,doneMsg2) "\"\$commNum comments were read (\$ignoreNum duplicated)\""

set t(readTypeList,title)    "Open type list"
set t(readTypeList,errMsg)   "Could not read the type list (\$v(typeListFile))"
set t(readTypeList,errMsg2)  "Could not read the type list"
set t(readTypeList,doneMsg)  "\$v(typeListFile) was read"

set t(choosesaveDir,title)   "Choose save folder"
set t(choosesaveDir,doneMsg) "The save folder was changed"
set t(choosesaveDir,q)       "Read the oto.ini file too?"

set t(saveWavFile,doneMsg)   "Saved \$v(saveDir)/\$v(recLab)\$v(typeLab).wav"

set t(waitWindow,title)      "Calculating F0"

set t(bgmGuide,title)  "Recording mode"
set t(bgmGuide,mode)   "Mode:"
set t(bgmGuide,r1)     "Manual. Recording while 'r' is held down (same as OREMO 1.0)."
set t(bgmGuide,r2)     "Auto 1. 'r' plays the BGM once and records automatically. Move to the next item manually."
set t(bgmGuide,r3)     "Auto 2. 'r' loops the BGM, records automatically and moves to the next item automatically."
set t(bgmGuide,r4)     "Disabled."
set t(bgmGuide,bgm)    "BGM file:"
set t(bgmGuide,bTitle) "Choose BGM file"
set t(bgmGuide,play)   "Play"
set t(bgmGuide,stop)   "Stop"
set t(bgmGuide,tplay)  "Listen to a sample:"

set t(testPlayBGM,errMsg)   "Could not read the file"
set t(testPlayBGM,errTitle) "Playback error"

set t(tempoGuide,title)             "Metronome"
set t(tempoGuide,click)             "Click sound:"
set t(tempoGuide,clickTitle)        "Choose click sound"
set t(tempoGuide,tempo)             "Tempo:"
set t(tempoGuide,bpm)               "BPM = "
set t(tempoGuide,bpmUnit)           "msec/beat"
set t(tempoGuide,comment)           "* 'm' starts / stops the metronome."

set t(pitchGuide,title)             "Tuning fork"
set t(pitchGuide,sel)               "Guide tone:"
set t(pitchGuide,vol)               "Volume:"
set t(pitchGuide,comment)           "* Keys: o, up/down arrows, 2,4,6,8, ESC"

set t(genParam,title)  "oto.ini for continuous recordings"
set t(genParam,tempo)  "Tempo:"
set t(genParam,bpm)    "unit: bpm"
set t(genParam,S)      "Start of utterance:"
set t(genParam,unit)   "unit:"
set t(genParam,haku)   "beat"
set t(genParam,darrow) "↓　↓"
set t(genParam,bInit)  "Initialize the parameters from the tempo"
set t(genParam,O)      "Overlap:"
set t(genParam,msec)   "unit: msec"
set t(genParam,P)      "Preutterance:"
set t(genParam,C)      "Consonant:"
set t(genParam,E)      "Cutoff:"
set t(genParam,do)     "Generate"
set t(genParam,aliasMax)          "* Add numbers to duplicated aliases?"
set t(genParam,aliasMaxNo)        "No (keep duplicates)"
set t(genParam,aliasMaxYes)       "Yes"
set t(genParam,aliasMaxNum)       "Max number (0 = unlimited)"
set t(genParam,autoAdjustRen)     "Use auto correction 1 (power based)"
set t(genParam,vLow)              "Power dip at preutterance:"
set t(genParam,sRange)            "Search range of preutterance:"
set t(genParam,f0pow)             "* F0 and power settings are used as well."
set t(genParam,db)                "unit: dB"
set t(genParam,autoAdjustRen2)    "Use auto correction 2 (MFCC based, slow)"
set t(genParam,autoAdjustRen2Opt) "Options"
set t(genParam,autoAdjustRen2Pattern) "Target morae"

set t(doGenParam,doneMsg) "\$v(paramFile) was generated"

set t(checkWavForOREMO,saveQ)  "The wav shown now is not saved."
set t(checkWavForOREMO,saveA1) "Save and continue"
set t(checkWavForOREMO,saveA2) "Continue without saving"
set t(checkWavForOREMO,saveA3) "Cancel"

set t(searchParam,title)     "Search"
set t(searchParam,search)    "Search"
set t(searchParam,rup)       "Up"
set t(searchParam,rdown)     "Down"
set t(searchParam,doneTitle) "Search finished"
set t(searchParam,doneMsg)   "Not found."

set t(autoRecStart,errMsg)   "Could not read the BGM file (\$v(bgmFile))"
set t(autoRecStart,errMsg2)  "Could not read the BGM setting file \$v(bgmParamFile)"
set t(autoRecStart,errMsg3)  "Invalid time unit"
set t(autoRecStart,errMsg4)  "The last line of the setting file (\$v(bgmParamFile)) must have a repeat."
set t(autoRecStart,unit)     "unit"

set t(autoRecStop,doneMsg)   "Automatic recording stopped"

set t(toggleMetroPlay,stopMsg)  "Metronome stopped"
set t(toggleMetroPlay,errTitle) "Metronome error"
set t(toggleMetroPlay,errMsg)   "The tempo must be between 50 and 200 bpm."
set t(toggleMetroPlay,errMsg2)  "The click wav file (\$v(clickWav)) was not found."
set t(toggleMetroPlay,playMsg)  "Metronome playing... ('m' to stop)"
set t(toggleMetroPlay,errPa)  "Could not play the metronome."

set t(toggleOnsaPlay,stopMsg) "Tuning fork stopped"
set t(toggleOnsaPlay,playMsg) "Tuning fork playing... ('o' to stop)"

set t(togglePlay,stopMsg) "Stopped"
set t(togglePlay,playMsg) "Playing..."

set t(chooseColor,title) "Choose color"
set t(setColor,selColor) "Choose color"

set t(packToneList,play)   "Play"
set t(packToneList,repeat) "Repeat"

set t(saveSettings,title)  "Save init file"

set t(setIODevice,errPa)  "Could not set up the audio device."
set t(setIODevice,errPa2) "Choose an input device for PortAudio."
set t(setIODevice,errPa3) "Check the number of input channels."
set t(setIODevice,errPa4) "Check the sampling rate."
set t(setIODevice,errPa5) "Check the buffer size."
set t(setIODevice,errPaOut2) "Choose an output device for PortAudio."

set t(ioSettings,title)    "Audio I/O settings"
set t(ioSettings,inDev)    "Input device:"
set t(ioSettings,outDev)   "Output device:"
set t(ioSettings,inGain)   "Input gain (may not work):"
set t(ioSettings,outGain)  "Output gain (may not work):"
set t(ioSettings,latency)  "Latency (may not work):"
set t(ioSettings,sndBuffer) "Recording buffer size:"
set t(ioSettings,bgmBuffer) "Guide BGM buffer size:"
set t(ioSettings,comment0) "* Keep the defaults (device = Sound Mapper / Wave Mapper) if possible."
set t(ioSettings,comment0b) "  Other drivers such as DirectSound may be unstable."
set t(ioSettings,comment1) "* Press 'Apply' or 'OK' after changing the settings."
set t(ioSettings,comment2) "  Otherwise they are not applied."
set t(ioSettings,useRequestRec)  "Record"
set t(ioSettings,useRequestPlay) "Play"
set t(ioSettings,sampleRate) "Sampling rate (Hz):"
set t(ioSettings,format)     "Format (bits):"
set t(ioSettings,inChannel)  "Input channels:"
set t(ioSettings,bufferSize)  "Buffer size:"
set t(ioSettings,portaudio)   "PortAudio:"

set t(estimateParam,title)       "Estimate parameters (single)"
set t(estimateParam,pFLen)       "Power frame interval"
set t(estimateParam,preemph)     "Pre-emphasis"
set t(estimateParam,pWinLen)     "Power window length"
set t(estimateParam,pWinkind)    "Window type"
set t(estimateParam,pUttMin)     "Min power in utterance"
set t(estimateParam,vLow)        "Min power of vowel"
set t(estimateParam,pUttMinTime) "Min utterance length"
set t(estimateParam,uttLen)      "Power fluctuation in utterance"
set t(estimateParam,silMax)      "Max power in silence"
set t(estimateParam,silMinTime)  "Min silence length"
set t(estimateParam,minC)        "Min consonant length"
set t(estimateParam,f0)          "* F0 settings are used as well."
set t(estimateParam,target)      "Estimate"
set t(estimateParam,S)           "Offset"
set t(estimateParam,C)           "Consonant"
set t(estimateParam,E)           "Cutoff"
set t(estimateParam,P)           "Preutterance"
set t(estimateParam,O)           "Overlap"
set t(estimateParam,overWrite)   "The current parameters will be overwritten. OK?"
set t(estimateParam,runAll)      "Run for all wavs"
set t(estimateParam,runSel)      "Run for selection"

set t(doEstimateParam,startMsg)  "Estimating parameters... "
set t(doEstimateParam,doneMsg)   "Parameter estimation finished"

set t(readParamFile,selMsg)   "Choose oto.ini"
set t(readParamFile,startMsg) "Reading oto.ini..."
set t(readParamFile,errMsg)   "\$v(paramFile) refers to wav files not in \$v(saveDir)/."
set t(readParamFile,example)  "e.g.:"
set t(readParamFile,errMsg2)  "\$v(paramFile) lacks entries; they are added."
set t(readParamFile,doneMsg)  "\$v(paramFile) was read"

set t(saveParamFile,selFile)  "Save oto.ini"
set t(saveParamFile,startMsg) "Saving oto.ini... "
set t(saveParamFile,doneMsg)  "oto.ini was saved"

set t(settings,title)        "Detailed settings"
set t(settings,wave)         "<Waveform>"
set t(settings,waveColor)    "Waveform color:"
set t(settings,waveScale)    "Max value of the axis (0-32768, 0=auto)"
set t(settings,sampleRate)   "Sampling rate (Hz):"
set t(settings,spec)         "<Spectrogram>"
set t(settings,specColor)    "Colors:"
set t(settings,maxFreq)      "Max frequency (Hz):"
set t(settings,brightness)   "Brightness:"
set t(settings,contrast)     "Contrast:"
set t(settings,fftLength)    "FFT length (samples):"
set t(settings,fftWinLength) "Window length (samples):"
set t(settings,fftPreemph)   "Pre-emphasis:"
set t(settings,fftWinKind)   "Window type"
set t(settings,pow)          "<Power>"
set t(settings,powColor)     "Power curve color:"
set t(settings,powLength)    "Frame interval (sec):"
set t(settings,powPreemph)   "Pre-emphasis:"
set t(settings,winLength)    "Window length (sec):"
set t(settings,powWinKind)   "Window type:"
set t(settings,f0)           "<F0 (pitch)>"
set t(settings,f0Color)      "F0 curve color:"
set t(settings,f0Argo)       "Algorithm:"
set t(settings,f0Length)     "Frame interval (sec):"
set t(settings,f0WinLength)  "Window length (sec):"
set t(settings,f0Max)        "Max F0 (Hz):"
set t(settings,f0Min)        "Min F0 (Hz):"
set t(settings,f0Unit)       "Unit:"
set t(settings,f0FixRange)   "Fix the display range"
set t(settings,f0FixRange,h) "Max:"
set t(settings,f0FixRange,l) "Min:"
set t(settings,grid)         "Draw a line for each note"
set t(settings,gridColor)    "Line color:"
set t(settings,target)       "Draw the target note"
set t(settings,targetTone)   "Target:"
set t(settings,targetColor)  "Line color:"
set t(settings,autoSetting)  "Adjust other settings to the target:"

set t(recStart,msg) "Recording..."
set t(recStart,errPa)  "Could not start recording."
set t(aRecStart,errPa)  "Could not start recording."
set t(aRecStop,errPa)  "Could not stop recording."
set t(paRecRun,errMsg) "Could not start the recorder"
set t(paRecRun,errDev) "No recording device available"
set t(paPlayRun,errMsg) "Could not start the player"
set t(paPlayRun,errDev) "No playback device available"
set t(recStop,msg)  "Recording stopped"
set t(recStop,errPa)  "Could not stop recording."

set t(Exit,q2) "The waveform shown now is not saved. What do you want to do?"
set t(Exit,a1) "Save and exit"
set t(Exit,a2) "Exit without saving"
set t(Exit,a3) "Don't exit"

set t(PopUpMenu,showWave)   "Waveform"
set t(PopUpMenu,showSpec)   "Spectrogram"
set t(PopUpMenu,showPow)    "Power"
set t(PopUpMenu,showF0)     "F0"
set t(PopUpMenu,pitchGuide) "Tuning fork window"
set t(PopUpMenu,tempoGuide) "Metronome"
set t(PopUpMenu,settings)   "Detailed settings"
set t(PopUpMenu,zoomTitle)  "Zoom"
set t(PopUpMenu,zoom100)    "x1 (whole wav)"
set t(PopUpMenu,zoom1000)   "x10"
set t(PopUpMenu,zoom5000)   "x50"
set t(PopUpMenu,zoom10000)  "x100"
set t(PopUpMenu,zoomMax)    "max"

set t(Version,msg) "Version"

set t(initParamU,0) "name"
set t(initParamU,1) "offset"
set t(initParamU,2) "overlap"
set t(initParamU,3) "preutterance"
set t(initParamU,4) "consonant"
set t(initParamU,5) "cutoff"
set t(initParamU,6) "alias"

set t(searchComment,title)     "Search"
set t(searchComment,search)    "Search"
set t(searchComment,rup)       "Up"
set t(searchComment,rdown)     "Down"
set t(searchComment,doneTitle) "Search finished"
set t(searchComment,doneMsg)   "Not found."
set t(searchComment,rMatch1)   "Whole match"
set t(searchComment,rMatch2)   "Partial match"

set t(bindWindow,record)      "Record start & stop"
set t(bindWindow,recStop)     "Stop auto recording"
set t(bindWindow,nextRec)     "Next item"
set t(bindWindow,prevRec)     "Previous item"
set t(bindWindow,nextType)    "Next type"
set t(bindWindow,prevType)    "Previous type"
set t(bindWindow,nextRec0)    "Next item (don't save)"
set t(bindWindow,prevRec0)    "Previous item (don't save)"
set t(bindWindow,nextType0)   "Next type (don't save)"
set t(bindWindow,prevType0)   "Previous type (don't save)"
set t(bindWindow,togglePlay)  "Play"
set t(bindWindow,toggleOnsaPlay)   "Tuning fork"
set t(bindWindow,toggleMetroPlay)  "Metronome"
set t(bindWindow,searchComment)    "Search comment"
set t(bindWindow,waveReload)  "Reload waveform"
set t(bindWindow,waveExpand)  "Zoom in"
set t(bindWindow,waveShrink)  "Zoom out"
set t(bindWindow,ex)          "(e.g.) a, A, Ctrl-a, Alt-a, Ctrl-Alt-a"
set t(bindWindow,ex2)         "(e.g.) space, F1, F2"
set t(bindWindow,ex3)         "* Keys assigned before are not released by changing the setting"
set t(bindWindow,errTitle)    "Key setting error"
set t(bindWindow,errMsg)      "\"Cannot apply the key setting ( \$value )\""

set t(fontWindow,attention)   "Takes effect after restarting"
set t(fontWindow,attention2)  "Not effective when autoSaveInitFile=0"
set t(fontWindow,lbfs)        "Current item font size"
set t(fontWindow,lfs)         "List font size"
set t(fontWindow,lcfs)        "Comment font size"

set t(isSetparamComment,q) "\"Read it as a setParam comment file together with \$iniFile?\""
